services:
  - type: web
    name: lavera
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: lavera-super-secret-luxury-key-2026
